name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      # --- PASO "UPLOAD ARTIFACT" DESCOMENTADO ---
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1 # <-- Asegúrate que esta línea está descomentada y usa @v2
        with: # <-- Asegúrate que esta línea está descomentada
          path: './build' # <-- Asegúrate que esta línea está descomentada
      # --- FIN PASO "UPLOAD ARTIFACT" ---

# --- JOB COMPLETO COMENTADO PARA DEBUG ---
# deploy:
#   environment:
#     name: github-pages
#     url: ${{ steps.deployment.outputs.page_url }}
#   runs-on: ubuntu-latest
#   needs: build
#   steps:
#     - name: Deploy to GitHub Pages
#       id: deployment
#       uses: actions/deploy-pages@v2
# --- FIN JOB COMENTADO ---
